demo/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/salir', to: 'sessions#destroy'

  resources :activos

end

demo/app/models/activo.rb
class Activo < ActiveRecord::Base
end

demo/app/models/user.rb
class User < ActiveRecord::Base
	def self.from_omniauth(auth)
		User.create(
			nombre: auth['info']['name'],
			provider: auth['provider'],
			uid: auth['uid']
			)
		
	end
end

demo/app/controllers/activos_controller.rb
class ActivosController < ApplicationController
  before_action :set_activo, only: [:show, :edit, :update, :destroy]

  # GET /activos
  # GET /activos.json
  def index
    @activos = Activo.all
  end

  # GET /activos/1
  # GET /activos/1.json
  def show
  end

  # GET /activos/new
  def new
    @activo = Activo.new
  end

  # GET /activos/1/edit
  def edit
  end

  # POST /activos
  # POST /activos.json
  def create
    @activo = Activo.new(activo_params)

    respond_to do |format|
      if @activo.save
        format.html { redirect_to @activo, notice: 'Activo was successfully created.' }
        format.json { render :show, status: :created, location: @activo }
      else
        format.html { render :new }
        format.json { render json: @activo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activos/1
  # PATCH/PUT /activos/1.json
  def update
    respond_to do |format|
      if @activo.update(activo_params)
        format.html { redirect_to @activo, notice: 'Activo was successfully updated.' }
        format.json { render :show, status: :ok, location: @activo }
      else
        format.html { render :edit }
        format.json { render json: @activo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activos/1
  # DELETE /activos/1.json
  def destroy
    @activo.destroy
    respond_to do |format|
      format.html { redirect_to activos_url, notice: 'Activo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activo
      @activo = Activo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activo_params
      params.require(:activo).permit(:code, :name, :Description, :Department, :Manager, :invoice_number, :model, :date_admission, :state)
    end
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

demo/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

demo/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(env['omniauth.auth'])
		session[:user_id] = user.id 
		redirect_to :activos
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

demo/app/helpers/activos_helper.rb
module ActivosHelper
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/home_helper.rb
module HomeHelper
end

demo/app/helpers/sessions_helper.rb
module SessionsHelper
end

demo/app/views/activos/_form.html.erb
<%= form_for(@activo) do |f| %>
  <% if @activo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activo.errors.count, "error") %> prohibited this activo from being saved:</h2>

      <ul>
      <% @activo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form role="form">
  <div class="form-group">
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code , class: "form-control" %>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name , class: "form-control"%>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description , class: "form-control" %>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :Department %><br>
    <%= f.text_field :Department , class: "form-control" %>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :Manager %><br>
    <%= f.text_field :Manager , class: "form-control"%>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :invoice_number %><br>
    <%= f.text_field :invoice_number , class: "form-control" %>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model , class: "form-control" %>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :date_admission %><br>
    <%= f.date_select :date_admission %>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :state %><br>
    <%= f.number_field :state , class: "form-control"%>
  </div>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success btn-lg" %>
  </div>
</form>
<% end %>

demo/app/views/activos/edit.html.erb
<div class="container">
<h1>Editing Activo</h1>

<%= render 'form' %>

<%= link_to 'Show', @activo , class: "btn btn-warning" %> |
<%= link_to 'Back', activos_path , class: "btn btn-danger"%>
</div>

demo/app/views/activos/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<h1>Listing Activos</h1>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Code &nbsp;</th>
      <th>Name &nbsp;</th>
      <th>Description &nbsp;</th>
      <th>Department &nbsp;</th>
      <th>Manager &nbsp;</th>
      <th>Invoice number &nbsp;</th>
      <th>Model &nbsp;</th>
      <th>Date admission &nbsp;</th>
      <th>State &nbsp;</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activos.each do |activo| %>
      <tr>
        <td><%= activo.code %> </td>
        <td><%= activo.name %> </td>
        <td><%= activo.Description %> </td>
        <td><%= activo.Department %> </td>
        <td><%= activo.Manager %> </td>
        <td><%= activo.invoice_number %> </td>
        <td><%= activo.model %> </td>
        <td><%= activo.date_admission %> </td>
        <td><%= activo.state %> </td>
        <td><%= link_to 'Show', activo , class: "btn btn-success" %> &nbsp;</td>
        <td><%= link_to 'Edit', edit_activo_path(activo) , class: "btn btn-warning" %> &nbsp;</td>
        <td><%= link_to 'Destroy', activo, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %> &nbsp;</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activo', new_activo_path , class: "btn btn-primary btn-lg" %>
</div>

demo/app/views/activos/new.html.erb
<div class="container">
<h1>New Activo</h1>

<%= render 'form' %>

<%= link_to 'Back', activos_path , class: "btn btn-warning" %>

</div>

demo/app/views/activos/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>


<p>
  <strong>Code:</strong>
  <%= @activo.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @activo.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activo.Description %>
</p>

<p>
  <strong>Department:</strong>
  <%= @activo.Department %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @activo.Manager %>
</p>

<p>
  <strong>Invoice number:</strong>
  <%= @activo.invoice_number %>
</p>

<p>
  <strong>Model:</strong>
  <%= @activo.model %>
</p>

<p>
  <strong>Date admission:</strong>
  <%= @activo.date_admission %>
</p>

<p>
  <strong>State:</strong>
  <%= @activo.state %>
</p>

<%= link_to 'Edit', edit_activo_path(@activo) , class: "btn btn-warning" %> |
<%= link_to 'Back', activos_path , class: "btn btn-danger"%>
</div>

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ITSAE || Sistema de Control de Activos</title>
  <link rel="icon" href="LOGO_sistemas.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
  <!-- LINKS DE ESTILOS  -->
  <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/css/font-awesome.css">

  <!-- JAVASCRIPTS -->
  <script src="../../assets/javascript/jquery-1.11.2.min.js"></script>
  <script src="../../assets/javascript/bootstrap.min.js"></script>
</head>
<body>

<div class="container" style="min-height: 45em;padding-top:5em; width:100%;"> 

<div class="container ">
<% if current_user  %>
    <nav  class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Desplegar navegación</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>       
      </button>
      <a class="navbar-brand" href="http://www.itsae.edu.ec" >
      <img alt="Brand" src="LOGO_sistemas.png" style="height: 35px; width:45px;">
      </a>
       
    </div>
  

    <div class="collapse navbar-collapse navbar-ex1-collapse"> 
    
      <ul class="nav navbar-nav">
        <li><a href="/activos"><span style="color: white;" class="fa fa-list-alt"></span>&nbsp;Activos</a></li>        
       
      </ul>
  

  
      <ul class="nav navbar-nav navbar-right">
        <li><a href="javascript:window.print()"><span style="color: white;" class="fa fa-print"></span>&nbsp;Imprimir Pág</a></li>
        <li><a href="/salir"><span style="color: white;" class="fa fa-power-off"></span>&nbsp;Salir &emsp;&emsp; </a></li>
      </ul>
    </div>
  </nav>
    <div align="center">
    <h1> Welcome &nbsp; <b><%= current_user.nombre %></b></h1>
    </div>
  <% else %>
    <div class="container">
      <div align="center">
      <h1>Sistema de Control de Activos ITSAE-CADE 2016</h1>
      <h2>Ingresa por alguno de tus servidores favoritos</h2>
      <br><br>
      <table>
      <tr>
      <td><%= link_to '', '/auth/facebook' , class: "btn btn-primary btn-login fa fa-facebook-square fa-5x " %></td>
      </tr>
      <tr><td>&nbsp;</td></tr>
      <tr>
      <td><%= link_to '', '/auth/google_oauth2', class: "btn btn-danger btn-login fa fa-google-plus-square fa-5x"  %></td></tr>
      </table>
      </div>
    </div>
<% end %>
</div>


<%= yield %>

</div>

<footer>
  	<p align="center">  Copyright © 2016 Miguel Miño, Instituto Tecnológico Superior Adventista del Ecuador - ITSAE 
 </footer>


</body>
</html>